//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ayva.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_ayvaEntities : DbContext
    {
        public Db_ayvaEntities()
            : base("name=Db_ayvaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_ayvaUretim> Tbl_ayvaUretim { get; set; }
        public virtual DbSet<Tbl_iller> Tbl_iller { get; set; }
        public virtual DbSet<Tbl_slider> Tbl_slider { get; set; }
        public virtual DbSet<Tbl_users> Tbl_users { get; set; }
    }
}
