//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ayva.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Tbl_ayvaUretim
    {
        public int Id { get; set; }
        [DisplayName("Üretim Yýlý")]
        public Nullable<int> uYili { get; set; }
        [DisplayName("Üretim Miktarý")]
        public Nullable<double> uretimMiktari { get; set; }
        [DisplayName("Ýl")]
        public Nullable<int> ilID { get; set; }
    }
}
