//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ayva.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_users
    {
        public int Id { get; set; }

        [DisplayName("E-Mail")]
        [Required(ErrorMessage ="E-Mail alaný gereklidir.")]
        [EmailAddress(ErrorMessage = "E-Mail doðru formatta deðildir")]
        public string email { get; set; }

        [DisplayName("Þifre")]
        [Required]
        [MinLength(8,ErrorMessage ="Þifre en az 8 karakterden oluþmalýdýr.")]
        public string password { get; set; }
        public string role { get; set; }
    }
}
